-- Supabase Schema for StreamingTiktokHandlerAPP

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS rewards (
  name TEXT PRIMARY KEY,
  actions TEXT
);

CREATE TABLE IF NOT EXISTS reward_presets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  data TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS detected_gifts (
  name TEXT PRIMARY KEY,
  count INTEGER DEFAULT 1,
  last_seen TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_likes (
  username TEXT PRIMARY KEY,
  nickname TEXT,
  total_likes INTEGER DEFAULT 0,
  last_milestone INTEGER DEFAULT 0,
  last_updated TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS giveaway_participants (
  username TEXT PRIMARY KEY,
  nickname TEXT,
  profile_picture TEXT,
  has_followed INTEGER DEFAULT 0,
  has_liked INTEGER DEFAULT 0,
  has_shared INTEGER DEFAULT 0,
  has_commented INTEGER DEFAULT 0,
  has_wa_group INTEGER DEFAULT 0,
  wa_member_tag TEXT,
  wa_phone TEXT,
  is_eligible INTEGER DEFAULT 0,
  is_tester INTEGER DEFAULT 0,
  registered_at TIMESTAMPTZ DEFAULT NOW(),
  last_updated TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wa_group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_jid TEXT NOT NULL,
  jid TEXT NOT NULL,
  phone TEXT,
  member_tag TEXT,
  push_name TEXT,
  role TEXT,
  has_absen INTEGER DEFAULT 0,
  absen_at TIMESTAMPTZ,
  last_seen TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT wa_group_members_unique UNIQUE(group_jid, jid)
);

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO admin_users (username, password, role)
VALUES ('virtusx01', '@Almigty007', 'admin')
ON CONFLICT (username) DO UPDATE SET password = EXCLUDED.password;
